Add attribution option to plotting functions
palaeoverse-community/rphylopic pull request #79
Opened 2023-08-23 15:53 UTC by willgearty

This adds the `verbose` argument to our three plotting functions (geom_phylopic, add_phylopic, and add_phylopic_base) that outputs the get_attribution text for the silhouettes used. If the `name` aesthetic/argument is used in these functions (implying the user doesn't have a list of uuids or image objects in their environment), a warning is printed if `verbose` is not set to TRUE.

Fixes #71.

2023-08-23 16:42 UTC, keesey commented
Any thoughts about utilizing the `/collections` endpoints on _PhyloPic_ for attribution? You can link to pages like these: https://www.phylopic.org/collections/39f27cb5-5952-01d2-002a-0721a815ac14

There is also a way to turn those into permalinks, although I still need to document that for public usage.

2023-08-23 19:57 UTC, willgearty commented
@keesey Ah, I had always thought you needed to create collections in the web portal, but I see now you can generate them with the API. We'll look into incorporating that!

2023-08-23 20:00 UTC, willgearty commented
@keesey Are collection uuids essentially permalinks? In other words, will a collection URL always include the same list of images?

2023-08-25 13:14 UTC, LewisAJones requested changes
Hi @willgearty, this is looking pretty good and almost there. The main issue I see is that with `geom_phylopic` the warning message and attribution information is called for each unique name, see example: 

```
library(ggplot2)
df <- data.frame(x = c(2, 4), y = c(10, 20), name = c("cat", "walrus"))
# Multiple warning messages
ggplot(df) +
  geom_phylopic(aes(x = x, y = y, name = name),
                verbose = FALSE, color = "purple", size = 10) +
  facet_wrap(~name) +
  coord_cartesian(xlim = c(1,6), ylim = c(5, 30))
# Multiple attribution messages (should just be one).
ggplot(df) +
  geom_phylopic(aes(x = x, y = y, name = name),
                verbose = TRUE, color = "purple", size = 10) +
  facet_wrap(~name) +
  coord_cartesian(xlim = c(1,6), ylim = c(5, 30))
```

2023-08-25 13:14 UTC, LewisAJones commented on R/add_phylopic_base.r
> +      warning(paste("You've used the `name` argument. You may want to use",
Oppps nevermind, this covers my above comment well! Good job.

2023-08-25 13:14 UTC, LewisAJones commented on R/add_phylopic_base.r
> +                              remove_background = TRUE, verbose = FALSE) {
Error handling for verbose?

2023-08-25 13:14 UTC, LewisAJones commented on R/add_phylopic_base.r
> +                    "for the silhouettes."), call. = FALSE)
```suggestion
                    "for the silhouette(s)."), call. = FALSE)
```

2023-08-25 13:14 UTC, LewisAJones commented on R/geom_phylopic.R
> +                      "for the silhouettes."), call. = FALSE)
```suggestion
                      "for the silhouette(s)."), call. = FALSE)
```

2023-08-25 13:14 UTC, LewisAJones commented on R/add_phylopic.r
> +#'   used silhouettes be printed to the console (see [get_attribution()])?
```suggestion
#'   used silhouette(s) be printed to the console (see [get_attribution()])?
```

2023-08-25 17:24 UTC, willgearty commented
I think it's once per facet? I figured this was fine because often you list separate captions for each facet/panel of a figure anyways?

2023-08-25 17:35 UTC, LewisAJones commented
> I think it's once per facet/panel for geom_phylopic? I figured this was fine because often you list separate captions for each facet/panel of a figure anyways?

Maybe? I can just imagine a situation where you have many facets and you flood the console (like our LBG paper for example).

2023-08-25 17:39 UTC, willgearty commented
Hmm...that might require a complete refactoring of GeomPhylopic, then. We currently process the names/uuids/imgs on a per-panel basis (this is pretty standard for geoms), so we would need to move all of this processing to a different step of the geom construction process...

2023-08-25 17:56 UTC, LewisAJones commented
> Hmm...that might require a complete refactoring of GeomPhylopic, then. We currently process the names/uuids/imgs on a per-panel basis (this is pretty standard for geoms), so we would need to move all of this processing to a different step of the geom construction process. I'll look into it...

Sounds like an update for a later version. Happy with moving forward as is!

2023-08-25 19:30 UTC, willgearty commented
I decided to go ahead and make the change anyways. Let me know what you think @LewisAJones!

2023-08-25 21:33 UTC, keesey commented
> @keesey Are collection uuids essentially permalinks? In other words, will a collections/ URL always include the same list of images?

It will always include the same list of UUIDs, but it's always possible that images will be removed or details changed. (Although both of those are quite infrequent.) Collections can be turned into actual permalinks, which will never change, but I haven't moved that to the general API yet. (Not sure when I'll have bandwidth.)

2023-08-26 03:16 UTC, willgearty commented on R/add_phylopic.r
> +                         remove_background = TRUE, verbose = FALSE) {
I totally thought about this as well. I think a message on package load would be great! (but let's make that a separate issue)

2023-08-27 10:23 UTC, LewisAJones approved these changes
All seems good to me now @willgearty, thanks for addressing my previous concern in this PR! I hope it wasn't too much extra work.

2023-08-27 10:55 UTC, merged